HairSalonBotan/Models/AdminVM.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace HairSalonBotan.Models
{
    public class AdminVM
    {
        [Required]
        public string Emailadres { get; set; }
        [Required]
        public string Wachtwoord { get; set; }
    }
}

HairSalonBotan/Models/BehandelingVM.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using InterfaceUI;
using FactoryUI;
using System.ComponentModel.DataAnnotations;

namespace HairSalonBotan.Models
{
    public class BehandelingVM
    {
        public CategorieVM categorieVM = new CategorieVM();

        [Required]
        public int Id { get; set; }
        [Required]
        public string omschrijving { get; set; }
        [Required]
        public decimal bedrag { get; set; }
        [Required]
        public List<IBehandelingUi> behandelingUI = new List<IBehandelingUi>();
        public List<IBehandelingUi> geefAlleBehandelingVoorCategorie = new List<IBehandelingUi>();
    }
}

HairSalonBotan/Models/CategorieVM.cs
using InterfaceUI;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace HairSalonBotan.Models
{
    public class CategorieVM
    {
        [Required]
        public int categorieId { get; set; }
        [Required]
        public string categorienaam { get; set; }

        public List<ICategorieUI> categorieInfoUI = new List<ICategorieUI>();
    }
}

HairSalonBotan/Models/KapperszaakVM.cs
using InterfaceUI;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace HairSalonBotan.Models
{
    public class KapperszaakVM
    {
        public ProductVM productvm = new ProductVM();

        [Required]
        public int kapperszaakId { get; set; }
        [Required]
        public string naam { get; set; }
        
        [Required]
        public List<IProductUi> producten = new List<IProductUi>();
        [Required]
        public List<IAfspraakUi> afspraken = new List<IAfspraakUi>();
        [Required]
        public List<ICadeauKaartUi> cadeaukaarten  = new List<ICadeauKaartUi>();


    }
}

HairSalonBotan/Models/ProductVM.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace HairSalonBotan.Models
{
    public class ProductVM
    {
        [Required]
        public int productId { get; set; }
        [Required]
        public string titel { get; set; }
        [Required]
        public string omschrijving { get; set; }
        [Required]
        public string image { get; set; }
    }
}

HairSalonBotan/Controllers/BehandelingController.cs
using System.Web.Mvc;
using InterfaceUI;
using FactoryUI;
using HairSalonBotan.Models;

namespace HairSalonBotan.Controllers
{
    public class BehandelingController : Controller
    {
        IBehandelingCollectieUi behandelingCollectie = UIFactory.BehandelingCollectie();
        IBehandelingUi behandelingUI = UIFactory.Behandeling();
        ICategorieCollectieUi categorieCollectie = UIFactory.CategorieCollectie();

        BehandelingVM bhmodel = new BehandelingVM();

        [HttpGet]
        public ActionResult Behandelingen()
        {
            bhmodel.behandelingUI = behandelingCollectie.AlleBehandelingenOphalen();

            return View(bhmodel);
        }
        public ActionResult BehandelingDoorGevenAanCategorie(string categorieNaam)
        {
            bhmodel.geefAlleBehandelingVoorCategorie = behandelingCollectie.AlleBehandelingenVoorCategorie(categorieNaam);
            Session["categorieNaam"] = categorieNaam;

            return View(bhmodel);
        }

        public ActionResult BehandelingReserveren(BehandelingVM behandelingVM)
        {
            var categorienaam = Session["categorieNaam"] as string;

            Session["behandelingVM"] = behandelingVM;

            var behandeling = Session["behandelingVM"] as BehandelingVM;

            return View(behandelingVM);
        }

        [HttpGet]
        public ActionResult CreateBehandeling(BehandelingVM behandelingVM)
        {
            behandelingVM.categorieVM.categorieInfoUI = categorieCollectie.AlleCategorieenOphalen();
            return View(behandelingVM);
        }

        [HttpPost]
        public ActionResult CreateBehandeling(BehandelingVM behandelingVM, CategorieVM categorieVM)
        {
            try
            {
                //categorieInfo = new CategorieInfoUI(categorieVM.categorieId, categorieVM.categorienaam);

                //behandelingsinfo = new BehandelingsInfoUI(behandelingVM.behandelingsId, behandelingVM.omschrijving, behandelingVM.bedrag, categorieInfo);
                //behandelingCollectie.BehandelingToevoegen(behandelingsinfo, categorieInfo);

                return RedirectToAction("Behandelingen");
            }
            catch
            {
                return View();
            }
        }

        [HttpGet]
        public ActionResult Edit(int behandelingId)
        {
            //behandelingUI.BehandelingIDdoorGeven();
            //bhmodel.behandelingsId = behandelingId; 

            return View();
        }

        [HttpPost]
        public ActionResult Edit(int behandelingId, CategorieVM categorieVM, BehandelingVM behandelingVM)
        {
            //categorieInfo = new CategorieInfoUI(categorieVM.categorieId, categorieVM.categorienaam);

            //behandelingsinfo = new BehandelingsInfoUI(behandelingVM.behandelingsId, behandelingVM.omschrijving, behandelingVM.bedrag, categorieInfo);
            //behandelingUI.UpdateBehandeling(behandelingId, behandelingsinfo, categorieInfo);

            return RedirectToAction("Behandelingen");
        }

        [HttpGet]
        public ActionResult VerwijderBehandeling()
        {
            return View();
        }

        [HttpPost]
        public ActionResult VerwijderBehandeling(BehandelingVM behandeling)
        {
            behandelingCollectie.BehandelingVerwijderen(behandeling.Id);

            return RedirectToAction("Behandelingen");
        }
    }
}

HairSalonBotan/Controllers/CategorieController.cs
using FactoryUI;
using HairSalonBotan.Models;
using InterfaceUI;
using System.Web.Mvc;

namespace HairSalonBotan.Controllers
{
    public class CategorieController : Controller
    {
        ICategorieCollectieUi categorieCollectieUI = UIFactory.CategorieCollectie();
        CategorieVM categorieVM = new CategorieVM();

        [HttpGet]
        public ActionResult Categorieën()
        {
            categorieVM.categorieInfoUI = categorieCollectieUI.AlleCategorieenOphalen();
            return View(categorieVM);
        }
    }
}

HairSalonBotan/Controllers/KapperszaakController.cs
using System.Web.Mvc;
using InterfaceUI;
using FactoryUI;
using HairSalonBotan.Models;

namespace HairSalonBotan.Controllers
{
    public class KapperszaakController : Controller
    {
        IKapperszaakUi kapperszaakUI = UIFactory.Kapperszaak();
        IProductUi productUi = UIFactory.Product();


        public ActionResult LijstProducten()
        {
            KapperszaakVM kpmodel = new KapperszaakVM()
            {
                producten = kapperszaakUI.AlleProductenOphalen()
            };
            return View(kpmodel);
        }
        public ActionResult ProductenPagina()
        {
            KapperszaakVM kpmodel = new KapperszaakVM()
            {
                producten = kapperszaakUI.AlleProductenOphalen()
            };
            return View(kpmodel);
        }
        public ActionResult Inloggen(AdminVM adminVM)
        {
            return View();
        }

        [HttpGet]
        public ActionResult Create(KapperszaakVM kapperszaakVM)
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(ProductVM productvm, KapperszaakVM kapperszaakVM)
        {
            try
            {

                //kapperszaakUI.VoegProductToe(productInfoUI, kapperszaakInfoUI);

                return RedirectToAction("LijstProducten");
            }
            catch
            {
                return View();
            }
        }


        [HttpPost]
        public ActionResult ProductVerwijderen()
        {
            kapperszaakUI.ProductVerwijderen(productUi.Id);
            return RedirectToAction("LijstProducten");
        }
    }
}

HairSalonBotan/Views/Behandeling/BehandelingDoorGevenAanCategorie.cshtml
@model HairSalonBotan.Models.BehandelingVM

@{
    ViewBag.Title = "BehandelingDoorGevenAanCategorie";
}
<h2>BehandelingDoorGevenAanCategorie</h2>


<table class="table">
    <tr>

        <th>
            @Html.DisplayNameFor(model => model.omschrijving)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.bedrag)
        </th>
        <th></th>
    </tr>
    

    @foreach (var item in Model.geefAlleBehandelingVoorCategorie)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Omschrijving)
            </td>
            <td>
                € @Html.DisplayFor(modelItem => item.Bedrag)
            </td>
            <td>
                @Html.ActionLink("Kiezen", "BehandelingReserveren", new {id = item.Id, omschrijving = item.Omschrijving, bedrag = item.Bedrag}, new {@class = "btn btn-primary"})
            </td>
        </tr>
    }
</table>

HairSalonBotan/Views/Behandeling/BehandelingReserveren.cshtml
@model HairSalonBotan.Models.BehandelingVM

@{
    ViewBag.Title = "BehandelingReserveren";
}

<h2>BehandelingReserveren</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.omschrijving)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.bedrag)
        </th>
    </tr>

    <tr>
        <td>
            @Html.DisplayFor(modelItem => Model.omschrijving)
        </td>
        <td>
            @Html.DisplayFor(modelItem => Model.bedrag)
        </td>
    </tr>
</table>

HairSalonBotan/Views/Behandeling/Behandelingen.cshtml
@model HairSalonBotan.Models.BehandelingVM

@{
    ViewBag.Title = "Behandelingen";
}

<h2>Behandelingen</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.categorieVM.categorienaam)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.omschrijving)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.bedrag)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model.behandelingUI) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Categorie.Categorienaam)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Omschrijving)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Bedrag)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
            @Html.ActionLink("Delete", "VerwijderBehandeling", new { id = item.Id })
        </td>
    </tr>
}
</table>

HairSalonBotan/Views/Behandeling/Create.cshtml
@model HairSalonBotan.Models.BehandelingVM

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>BehandelingVM</h4>
    <hr />
    <div class="form-group">
        @Html.LabelFor(model => model.categorieVM.categorieId, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.categorieVM.categorieId, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.categorieVM.categorieId, "", new { @class = "text-danger" })
        </div>
    </div>
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.omschrijving, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.omschrijving, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.omschrijving, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.bedrag, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.bedrag, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.bedrag, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}


<div>
    @Html.ActionLink("Terug naar ", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

HairSalonBotan/Views/Behandeling/CreateBehandeling.cshtml
@model HairSalonBotan.Models.BehandelingVM

@{
    ViewBag.Title = "CreateBehandeling";
}

<h2>CreateBehandeling</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>BehandelingVM</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    <div class="form-group">
        @Html.LabelFor(model => model.categorieVM.categorienaam, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownListFor(CategorieNaam => CategorieNaam.categorieVM.categorieId, new SelectList(Model.categorieVM.categorieInfoUI, "categorieId", "categorienaam", "Select"))
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.omschrijving, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.omschrijving, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.omschrijving, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.bedrag, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.bedrag, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.bedrag, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Terug naar behandelingen", "Behandelingen")
</div>

HairSalonBotan/Views/Behandeling/Edit.cshtml
@model HairSalonBotan.Models.BehandelingVM

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>BehandelingVM</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.categorieVM.categorienaam, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(CategorieNaam => CategorieNaam.categorieVM.categorieId, new SelectList(Model.categorieVM.categorieInfoUI, "categorieId", "categorienaam", "Select"))
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.omschrijving, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.omschrijving, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.omschrijving, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.bedrag, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.bedrag, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.bedrag, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Behandelingen")
</div>

HairSalonBotan/Views/Behandeling/Index.cshtml
@model HairSalonBotan.Models.BehandelingVM

@{
    ViewBag.Title = "Index";
}
<h2>Index</h2>

<p>
    @Html.ActionLink("Voeg nieuw behandeling toe", "CreateBehandeling")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.categorieVM.categorienaam)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.omschrijving)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.bedrag)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model.behandelingUI)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.CategorieinfoUi.Categorienaam)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Omschrijving)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Bedrag)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { behandelingId = item.BehandelingsId }) |
                @Html.ActionLink("Delete", "VerwijderBehandeling",new { behandelingId = item.BehandelingsId })
            </td>
        </tr>
    }

</table>

HairSalonBotan/Views/Behandeling/LoggedInStatusMessage.cshtml
@model HairSalonBotan.Models.BehandelingVM

@{
    ViewBag.Title = "LoggedInStatusMessage";
}

<h2>BehandelingReserveren</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.categorieVM.categorienaam)
        </th>
    </tr>

    <tr>
        <td>
            @Html.DisplayFor(modelItem => Model.categorieVM.categorienaam)
        </td>
    </tr>
</table>

HairSalonBotan/Views/Behandeling/VerwijderBehandeling.cshtml
@model HairSalonBotan.Models.BehandelingVM

@{
    ViewBag.Title = "VerwijderBehandeling";
}

<h2>VerwijderBehandeling</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>BehandelingVM</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Id)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Id)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.omschrijving)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.omschrijving)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.bedrag)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.bedrag)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Behandelingen")
        </div>
    }
</div>

HairSalonBotan/Views/Categorie/Categorieën.cshtml
@model HairSalonBotan.Models.CategorieVM

@{
    ViewBag.Title = "Categorieën";
}

<br />
<h3>Afspraak Maken</h3>
<br />
<link href="~/Content/style.css" rel="stylesheet" />
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <div class="tabbable tabs-left">
                <ul class="nav nav-tabs">
                    @foreach (var item in Model.categorieInfoUI)
                    {
                        <li> @Html.ActionLink(item.Categorienaam, "BehandelingDoorGevenAanCategorie", "Behandeling", new {categorieNaam = item.Categorienaam }, null)</li>
                    }
                </ul>
            </div>
        </div>
    </div>
</div>

HairSalonBotan/Views/Kapperszaak/Create.cshtml
@model HairSalonBotan.Models.KapperszaakVM

@{
    ViewBag.Title = "CreateBehandeling";
}

<h2>CreateBehandeling</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>BehandelingVM</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.kapperszaakId, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.kapperszaakId, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.kapperszaakId, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.naam, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.naam, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.naam, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.productvm.titel, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.productvm.titel, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.productvm.titel, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.productvm.omschrijving, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.productvm.omschrijving, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.productvm.omschrijving, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.productvm.image, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <input type="file" id="images" name="images"/>
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Terug naar producten", "LijstProducten")
</div>

HairSalonBotan/Views/Kapperszaak/Index.cshtml
@model HairSalonBotan.Models.KapperszaakVM

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>


<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.titel)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.omschrijving)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.prijs)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.image)
        </th>
        <th></th>
    </tr>

    @foreach (var item in @Model.producten)
    {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.titel)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.omschrijving)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.prijs)
        </td>
        <td>
            <img src="@Url.Content(item.image)" width="250" height="200"/>
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
            @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
            @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
        </td>
    </tr>
    }

</table>

HairSalonBotan/Views/Kapperszaak/Inloggen.cshtml
@{
    ViewBag.Title = "Inloggen";
}

<html>
<head>
    <title> Login Pagina</title>
</head>
<body>
    <form asp-area="" asp-controller="Kapperszaak" asp-action="Inloggen" method="post">
        <div class="container_loginforum">
            <h2>Login</h2>
            <input type="text" name="Emailadres" placeholder="Enter Emailadres">
            <input type="password" name="Wachtwoord" placeholder="Enter Wachtwoord">
            <input class="inloggen" type="submit" value="Inloggen" />
        </div>
    </form>
</body>
</html>

HairSalonBotan/Views/Kapperszaak/LijstProducten.cshtml
@model HairSalonBotan.Models.KapperszaakVM

@{
    ViewBag.Title = "LijstProducten";
}

<h2>Producten</h2>
<p>
    @Html.ActionLink("Voeg nieuw product toe", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.productvm.titel)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.productvm.omschrijving)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.productvm.image)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model.producten)
    {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Titel)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Omschrijving)
        </td>
        <td>
            <img src="@Url.Content(item.Image)" width="250" height="200"/>
        </td>
        <td>
            @Html.ActionLink("Verwijder", "ProductVerwijderen", new { productId = item.Id })
        </td>
    </tr>
    }

</table>

HairSalonBotan/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <img src="~/Content/LogoHSB.jpg" title="core" alt="" width="100" height="70" />
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("HairSalon Botan", "LijstProducten", "Kapperszaak", new { area = "" }, new { @class = "navbar-brand" })                
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Behandeling", "Behandelingen", "Behandeling")</li>
                    <li>@Html.ActionLink("Producten", "ProductenPagina", "Kapperszaak")</li>
                    <li>@Html.ActionLink("Afspraak maken", "Categorieën", "Categorie")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>